### ISSUE TITLE
setting Kanban board for food recipe app group project

### ISSUE THREAD

**Issue by ZabihullahNooriWardak** [Estete9/recipes-app#16]
Hello dear reviewer . 
this is an issue providing link to our kanban board  and saying that we are 3 team members . 
link to kanban board : https://github.com/users/Estete9/projects/16

**Comment by topeogunleye** [comment]
Hi @ZabihullahNooriWardak, @Estete9, @simplegoose, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
## Project Info

- Has the Link to GitHub project. ✔️ 
- Had the Number of people in the group: ✔️ 

## Board Columns

- The board has the following columns: To Do, In Progress, In Review, Done. 👍
- [Optional] You could also add a column for Blocked or Waiting for Feedback, to indicate tasks that depend on external factors or require more input from others.

## Card Details

- Each card has a descriptive title, a number of points in the [Xpt] prefix, and a description of the task. 👍
- [Optional] You could also add labels or tags to categorize the cards by type, priority, or difficulty.

## Project Requirements

- The project requirements are clearly defined and each requirement has at least one corresponding card in the Kanban board. 👍
- [Optional] You could also link the cards to the issues or pull requests that implement them, to track the progress and status of each requirement.

## Task Assignment

- All cards are assigned to team members. 👍
- The tasks are distributed in a fair way. Each team member has a similar number of points. 👍
- [Optional] You could also use the board filters to see the workload and progress of each team member.

## Overall Feedback

- The project is well-organized and follows the best practices of Kanban. 👏
- The code is clean, readable, and follows the coding standards and guidelines. 👏
- The functionality and test coverage of the code are satisfactory and meet the project requirements. 👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
